server:
  port: 8082
  servlet:
    context-path: /api
  error:
    include-message: always

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: ${MAIL_EMAIL:tjava2021@gmail.com}
    password: ${MAIL_PASSWORD:Tjava2021@2021}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          quitwait: false

  datasource:
    url: jdbc:postgresql://localhost:5433/apus
    username: apus
    password: apus
  jpa:
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:user}
    password: ${RABBITMQ_PASSWORD:bitnami}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

app:
  lyra:
    url: ${LYRA_URL:https://apus-external.herokuapp.com/api/lyra/payment}
  apus:
    url: ${APUS_URL:https://apus-ecommerce.herokuapp.com/api}
#    url: ${APUS_URL:http://localhost:8081/api}
  job:
    # 1 hora
    time: ${JOB_TIME:3600000}
