name: Check Tests and Sonar
on:
  push:
    branches:
      - 'main'
      - 'feat**'
      - 'issue**'
jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Tests
        run: ./mvnw -B clean package -DskipTests=true
      - name: Sonar Analysis
        run: ./mvnw -B sonar:sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
